name: CI script for backend

on:
  pull_request:
    branches: [main]
  jobs:
    build:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v4
        - uses: actions/setup-node@v4
          with:
            node-version: 'latest'
        - run: npm i
        - name: Begin running tests
          run: npm run testcov
          working-directory: ./Backend/
        - name: Publish test results
          uses: EnricoMi/publish-unit-test-result-action@v2
          if: (!cancelled())
          with:
            files: |
              Backend/coverage/**/*.xml
              Backend/coverage/**/*.json
        - name: Upload coverage report to codecov
          uses: codecov/codecov-action@v5
          with:
            token: ${{ secrets.CODECOV_TOKEN }}
        - name: Format code using prettier
          uses: creyD/prettier_action@v4.5
          with:
            prettier_options: --write Backend/**/*.js
