name: CI script for backend
permissions:
  checks: write
  pull-requests: write

on:
  pull_request:
    branches: [main]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v4
        with:
          node-version: 'latest'

      - run: npm i
        working-directory: Backend/

      - name: Begin running tests
        run: ENV=test npx jest unit --coverage
        working-directory: ./Backend/

      - name: Publish test results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: (!cancelled())
        with:
          files: |
            Backend/coverage/results.xml

      - name: Upload coverage report to codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          files: Backend/coverage/lcov.info

      - name: Format code using prettier
        uses: creyD/prettier_action@v4.5
        with:
          prettier_options: --write Backend/**/*.js
